import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import ClientForm from "../components/Gifs";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Drunkiel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClientForm />
      <Footer />
    </div>
  );
};

export default Home;
